// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/stpnv0/EventBooker/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEventSvc creates a new instance of MockEventSvc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventSvc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventSvc {
	mock := &MockEventSvc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventSvc is an autogenerated mock type for the EventSvc type
type MockEventSvc struct {
	mock.Mock
}

type MockEventSvc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventSvc) EXPECT() *MockEventSvc_Expecter {
	return &MockEventSvc_Expecter{mock: &_m.Mock}
}

// CreateEvent provides a mock function for the type MockEventSvc
func (_mock *MockEventSvc) CreateEvent(ctx context.Context, input domain.CreateEventInput) (*domain.Event, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateEvent")
	}

	var r0 *domain.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.CreateEventInput) (*domain.Event, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.CreateEventInput) *domain.Event); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.CreateEventInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventSvc_CreateEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEvent'
type MockEventSvc_CreateEvent_Call struct {
	*mock.Call
}

// CreateEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - input domain.CreateEventInput
func (_e *MockEventSvc_Expecter) CreateEvent(ctx interface{}, input interface{}) *MockEventSvc_CreateEvent_Call {
	return &MockEventSvc_CreateEvent_Call{Call: _e.mock.On("CreateEvent", ctx, input)}
}

func (_c *MockEventSvc_CreateEvent_Call) Run(run func(ctx context.Context, input domain.CreateEventInput)) *MockEventSvc_CreateEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.CreateEventInput
		if args[1] != nil {
			arg1 = args[1].(domain.CreateEventInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventSvc_CreateEvent_Call) Return(event *domain.Event, err error) *MockEventSvc_CreateEvent_Call {
	_c.Call.Return(event, err)
	return _c
}

func (_c *MockEventSvc_CreateEvent_Call) RunAndReturn(run func(ctx context.Context, input domain.CreateEventInput) (*domain.Event, error)) *MockEventSvc_CreateEvent_Call {
	_c.Call.Return(run)
	return _c
}

// GetDetails provides a mock function for the type MockEventSvc
func (_mock *MockEventSvc) GetDetails(ctx context.Context, id string) (*domain.EventDetails, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetDetails")
	}

	var r0 *domain.EventDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.EventDetails, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.EventDetails); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.EventDetails)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventSvc_GetDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDetails'
type MockEventSvc_GetDetails_Call struct {
	*mock.Call
}

// GetDetails is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockEventSvc_Expecter) GetDetails(ctx interface{}, id interface{}) *MockEventSvc_GetDetails_Call {
	return &MockEventSvc_GetDetails_Call{Call: _e.mock.On("GetDetails", ctx, id)}
}

func (_c *MockEventSvc_GetDetails_Call) Run(run func(ctx context.Context, id string)) *MockEventSvc_GetDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventSvc_GetDetails_Call) Return(eventDetails *domain.EventDetails, err error) *MockEventSvc_GetDetails_Call {
	_c.Call.Return(eventDetails, err)
	return _c
}

func (_c *MockEventSvc_GetDetails_Call) RunAndReturn(run func(ctx context.Context, id string) (*domain.EventDetails, error)) *MockEventSvc_GetDetails_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockEventSvc
func (_mock *MockEventSvc) List(ctx context.Context) ([]*domain.Event, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*domain.Event, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*domain.Event); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventSvc_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockEventSvc_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockEventSvc_Expecter) List(ctx interface{}) *MockEventSvc_List_Call {
	return &MockEventSvc_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockEventSvc_List_Call) Run(run func(ctx context.Context)) *MockEventSvc_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventSvc_List_Call) Return(events []*domain.Event, err error) *MockEventSvc_List_Call {
	_c.Call.Return(events, err)
	return _c
}

func (_c *MockEventSvc_List_Call) RunAndReturn(run func(ctx context.Context) ([]*domain.Event, error)) *MockEventSvc_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBookingSvc creates a new instance of MockBookingSvc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingSvc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingSvc {
	mock := &MockBookingSvc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBookingSvc is an autogenerated mock type for the BookingSvc type
type MockBookingSvc struct {
	mock.Mock
}

type MockBookingSvc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingSvc) EXPECT() *MockBookingSvc_Expecter {
	return &MockBookingSvc_Expecter{mock: &_m.Mock}
}

// Book provides a mock function for the type MockBookingSvc
func (_mock *MockBookingSvc) Book(ctx context.Context, eventID string, userID string) (*domain.Booking, error) {
	ret := _mock.Called(ctx, eventID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Book")
	}

	var r0 *domain.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*domain.Booking, error)); ok {
		return returnFunc(ctx, eventID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *domain.Booking); ok {
		r0 = returnFunc(ctx, eventID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, eventID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingSvc_Book_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Book'
type MockBookingSvc_Book_Call struct {
	*mock.Call
}

// Book is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
//   - userID string
func (_e *MockBookingSvc_Expecter) Book(ctx interface{}, eventID interface{}, userID interface{}) *MockBookingSvc_Book_Call {
	return &MockBookingSvc_Book_Call{Call: _e.mock.On("Book", ctx, eventID, userID)}
}

func (_c *MockBookingSvc_Book_Call) Run(run func(ctx context.Context, eventID string, userID string)) *MockBookingSvc_Book_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBookingSvc_Book_Call) Return(booking *domain.Booking, err error) *MockBookingSvc_Book_Call {
	_c.Call.Return(booking, err)
	return _c
}

func (_c *MockBookingSvc_Book_Call) RunAndReturn(run func(ctx context.Context, eventID string, userID string) (*domain.Booking, error)) *MockBookingSvc_Book_Call {
	_c.Call.Return(run)
	return _c
}

// Confirm provides a mock function for the type MockBookingSvc
func (_mock *MockBookingSvc) Confirm(ctx context.Context, eventID string, userID string) error {
	ret := _mock.Called(ctx, eventID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Confirm")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, eventID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBookingSvc_Confirm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Confirm'
type MockBookingSvc_Confirm_Call struct {
	*mock.Call
}

// Confirm is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
//   - userID string
func (_e *MockBookingSvc_Expecter) Confirm(ctx interface{}, eventID interface{}, userID interface{}) *MockBookingSvc_Confirm_Call {
	return &MockBookingSvc_Confirm_Call{Call: _e.mock.On("Confirm", ctx, eventID, userID)}
}

func (_c *MockBookingSvc_Confirm_Call) Run(run func(ctx context.Context, eventID string, userID string)) *MockBookingSvc_Confirm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBookingSvc_Confirm_Call) Return(err error) *MockBookingSvc_Confirm_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBookingSvc_Confirm_Call) RunAndReturn(run func(ctx context.Context, eventID string, userID string) error) *MockBookingSvc_Confirm_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function for the type MockBookingSvc
func (_mock *MockBookingSvc) ListByUser(ctx context.Context, userID string) ([]*domain.Booking, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []*domain.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*domain.Booking, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*domain.Booking); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingSvc_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockBookingSvc_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockBookingSvc_Expecter) ListByUser(ctx interface{}, userID interface{}) *MockBookingSvc_ListByUser_Call {
	return &MockBookingSvc_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID)}
}

func (_c *MockBookingSvc_ListByUser_Call) Run(run func(ctx context.Context, userID string)) *MockBookingSvc_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingSvc_ListByUser_Call) Return(bookings []*domain.Booking, err error) *MockBookingSvc_ListByUser_Call {
	_c.Call.Return(bookings, err)
	return _c
}

func (_c *MockBookingSvc_ListByUser_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*domain.Booking, error)) *MockBookingSvc_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserSvc creates a new instance of MockUserSvc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserSvc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserSvc {
	mock := &MockUserSvc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserSvc is an autogenerated mock type for the UserSvc type
type MockUserSvc struct {
	mock.Mock
}

type MockUserSvc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserSvc) EXPECT() *MockUserSvc_Expecter {
	return &MockUserSvc_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserSvc
func (_mock *MockUserSvc) Create(ctx context.Context, input domain.CreateUserInput) (*domain.User, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.CreateUserInput) (*domain.User, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.CreateUserInput) *domain.User); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.CreateUserInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserSvc_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserSvc_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - input domain.CreateUserInput
func (_e *MockUserSvc_Expecter) Create(ctx interface{}, input interface{}) *MockUserSvc_Create_Call {
	return &MockUserSvc_Create_Call{Call: _e.mock.On("Create", ctx, input)}
}

func (_c *MockUserSvc_Create_Call) Run(run func(ctx context.Context, input domain.CreateUserInput)) *MockUserSvc_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.CreateUserInput
		if args[1] != nil {
			arg1 = args[1].(domain.CreateUserInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserSvc_Create_Call) Return(user *domain.User, err error) *MockUserSvc_Create_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserSvc_Create_Call) RunAndReturn(run func(ctx context.Context, input domain.CreateUserInput) (*domain.User, error)) *MockUserSvc_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockUserSvc
func (_mock *MockUserSvc) List(ctx context.Context) ([]*domain.User, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*domain.User, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*domain.User); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserSvc_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockUserSvc_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUserSvc_Expecter) List(ctx interface{}) *MockUserSvc_List_Call {
	return &MockUserSvc_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockUserSvc_List_Call) Run(run func(ctx context.Context)) *MockUserSvc_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserSvc_List_Call) Return(users []*domain.User, err error) *MockUserSvc_List_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserSvc_List_Call) RunAndReturn(run func(ctx context.Context) ([]*domain.User, error)) *MockUserSvc_List_Call {
	_c.Call.Return(run)
	return _c
}
