// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/stpnv0/EventBooker/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBookingCanceller creates a new instance of MockBookingCanceller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingCanceller(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingCanceller {
	mock := &MockBookingCanceller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBookingCanceller is an autogenerated mock type for the BookingCanceller type
type MockBookingCanceller struct {
	mock.Mock
}

type MockBookingCanceller_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingCanceller) EXPECT() *MockBookingCanceller_Expecter {
	return &MockBookingCanceller_Expecter{mock: &_m.Mock}
}

// CancelExpired provides a mock function for the type MockBookingCanceller
func (_mock *MockBookingCanceller) CancelExpired(ctx context.Context) ([]*domain.Booking, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CancelExpired")
	}

	var r0 []*domain.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*domain.Booking, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*domain.Booking); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingCanceller_CancelExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelExpired'
type MockBookingCanceller_CancelExpired_Call struct {
	*mock.Call
}

// CancelExpired is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBookingCanceller_Expecter) CancelExpired(ctx interface{}) *MockBookingCanceller_CancelExpired_Call {
	return &MockBookingCanceller_CancelExpired_Call{Call: _e.mock.On("CancelExpired", ctx)}
}

func (_c *MockBookingCanceller_CancelExpired_Call) Run(run func(ctx context.Context)) *MockBookingCanceller_CancelExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBookingCanceller_CancelExpired_Call) Return(bookings []*domain.Booking, err error) *MockBookingCanceller_CancelExpired_Call {
	_c.Call.Return(bookings, err)
	return _c
}

func (_c *MockBookingCanceller_CancelExpired_Call) RunAndReturn(run func(ctx context.Context) ([]*domain.Booking, error)) *MockBookingCanceller_CancelExpired_Call {
	_c.Call.Return(run)
	return _c
}
