// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/stpnv0/EventBooker/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBookingRepo creates a new instance of MockBookingRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingRepo {
	mock := &MockBookingRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBookingRepo is an autogenerated mock type for the BookingRepo type
type MockBookingRepo struct {
	mock.Mock
}

type MockBookingRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingRepo) EXPECT() *MockBookingRepo_Expecter {
	return &MockBookingRepo_Expecter{mock: &_m.Mock}
}

// CancelExpired provides a mock function for the type MockBookingRepo
func (_mock *MockBookingRepo) CancelExpired(ctx context.Context) ([]*domain.Booking, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CancelExpired")
	}

	var r0 []*domain.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*domain.Booking, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*domain.Booking); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingRepo_CancelExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelExpired'
type MockBookingRepo_CancelExpired_Call struct {
	*mock.Call
}

// CancelExpired is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBookingRepo_Expecter) CancelExpired(ctx interface{}) *MockBookingRepo_CancelExpired_Call {
	return &MockBookingRepo_CancelExpired_Call{Call: _e.mock.On("CancelExpired", ctx)}
}

func (_c *MockBookingRepo_CancelExpired_Call) Run(run func(ctx context.Context)) *MockBookingRepo_CancelExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBookingRepo_CancelExpired_Call) Return(bookings []*domain.Booking, err error) *MockBookingRepo_CancelExpired_Call {
	_c.Call.Return(bookings, err)
	return _c
}

func (_c *MockBookingRepo_CancelExpired_Call) RunAndReturn(run func(ctx context.Context) ([]*domain.Booking, error)) *MockBookingRepo_CancelExpired_Call {
	_c.Call.Return(run)
	return _c
}

// Confirm provides a mock function for the type MockBookingRepo
func (_mock *MockBookingRepo) Confirm(ctx context.Context, eventID string, userID string) error {
	ret := _mock.Called(ctx, eventID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Confirm")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, eventID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBookingRepo_Confirm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Confirm'
type MockBookingRepo_Confirm_Call struct {
	*mock.Call
}

// Confirm is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
//   - userID string
func (_e *MockBookingRepo_Expecter) Confirm(ctx interface{}, eventID interface{}, userID interface{}) *MockBookingRepo_Confirm_Call {
	return &MockBookingRepo_Confirm_Call{Call: _e.mock.On("Confirm", ctx, eventID, userID)}
}

func (_c *MockBookingRepo_Confirm_Call) Run(run func(ctx context.Context, eventID string, userID string)) *MockBookingRepo_Confirm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBookingRepo_Confirm_Call) Return(err error) *MockBookingRepo_Confirm_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBookingRepo_Confirm_Call) RunAndReturn(run func(ctx context.Context, eventID string, userID string) error) *MockBookingRepo_Confirm_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockBookingRepo
func (_mock *MockBookingRepo) Create(ctx context.Context, b *domain.Booking) error {
	ret := _mock.Called(ctx, b)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Booking) error); ok {
		r0 = returnFunc(ctx, b)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBookingRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBookingRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - b *domain.Booking
func (_e *MockBookingRepo_Expecter) Create(ctx interface{}, b interface{}) *MockBookingRepo_Create_Call {
	return &MockBookingRepo_Create_Call{Call: _e.mock.On("Create", ctx, b)}
}

func (_c *MockBookingRepo_Create_Call) Run(run func(ctx context.Context, b *domain.Booking)) *MockBookingRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Booking
		if args[1] != nil {
			arg1 = args[1].(*domain.Booking)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingRepo_Create_Call) Return(err error) *MockBookingRepo_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBookingRepo_Create_Call) RunAndReturn(run func(ctx context.Context, b *domain.Booking) error) *MockBookingRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEventAndUser provides a mock function for the type MockBookingRepo
func (_mock *MockBookingRepo) GetByEventAndUser(ctx context.Context, eventID string, userID string) (*domain.Booking, error) {
	ret := _mock.Called(ctx, eventID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByEventAndUser")
	}

	var r0 *domain.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*domain.Booking, error)); ok {
		return returnFunc(ctx, eventID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *domain.Booking); ok {
		r0 = returnFunc(ctx, eventID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, eventID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingRepo_GetByEventAndUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEventAndUser'
type MockBookingRepo_GetByEventAndUser_Call struct {
	*mock.Call
}

// GetByEventAndUser is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
//   - userID string
func (_e *MockBookingRepo_Expecter) GetByEventAndUser(ctx interface{}, eventID interface{}, userID interface{}) *MockBookingRepo_GetByEventAndUser_Call {
	return &MockBookingRepo_GetByEventAndUser_Call{Call: _e.mock.On("GetByEventAndUser", ctx, eventID, userID)}
}

func (_c *MockBookingRepo_GetByEventAndUser_Call) Run(run func(ctx context.Context, eventID string, userID string)) *MockBookingRepo_GetByEventAndUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBookingRepo_GetByEventAndUser_Call) Return(booking *domain.Booking, err error) *MockBookingRepo_GetByEventAndUser_Call {
	_c.Call.Return(booking, err)
	return _c
}

func (_c *MockBookingRepo_GetByEventAndUser_Call) RunAndReturn(run func(ctx context.Context, eventID string, userID string) (*domain.Booking, error)) *MockBookingRepo_GetByEventAndUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListByEvent provides a mock function for the type MockBookingRepo
func (_mock *MockBookingRepo) ListByEvent(ctx context.Context, eventID string) ([]*domain.Booking, error) {
	ret := _mock.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for ListByEvent")
	}

	var r0 []*domain.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*domain.Booking, error)); ok {
		return returnFunc(ctx, eventID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*domain.Booking); ok {
		r0 = returnFunc(ctx, eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingRepo_ListByEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByEvent'
type MockBookingRepo_ListByEvent_Call struct {
	*mock.Call
}

// ListByEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
func (_e *MockBookingRepo_Expecter) ListByEvent(ctx interface{}, eventID interface{}) *MockBookingRepo_ListByEvent_Call {
	return &MockBookingRepo_ListByEvent_Call{Call: _e.mock.On("ListByEvent", ctx, eventID)}
}

func (_c *MockBookingRepo_ListByEvent_Call) Run(run func(ctx context.Context, eventID string)) *MockBookingRepo_ListByEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingRepo_ListByEvent_Call) Return(bookings []*domain.Booking, err error) *MockBookingRepo_ListByEvent_Call {
	_c.Call.Return(bookings, err)
	return _c
}

func (_c *MockBookingRepo_ListByEvent_Call) RunAndReturn(run func(ctx context.Context, eventID string) ([]*domain.Booking, error)) *MockBookingRepo_ListByEvent_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function for the type MockBookingRepo
func (_mock *MockBookingRepo) ListByUser(ctx context.Context, userID string) ([]*domain.Booking, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []*domain.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*domain.Booking, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*domain.Booking); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingRepo_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockBookingRepo_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockBookingRepo_Expecter) ListByUser(ctx interface{}, userID interface{}) *MockBookingRepo_ListByUser_Call {
	return &MockBookingRepo_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID)}
}

func (_c *MockBookingRepo_ListByUser_Call) Run(run func(ctx context.Context, userID string)) *MockBookingRepo_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingRepo_ListByUser_Call) Return(bookings []*domain.Booking, err error) *MockBookingRepo_ListByUser_Call {
	_c.Call.Return(bookings, err)
	return _c
}

func (_c *MockBookingRepo_ListByUser_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*domain.Booking, error)) *MockBookingRepo_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventRepo creates a new instance of MockEventRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventRepo {
	mock := &MockEventRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventRepo is an autogenerated mock type for the EventRepo type
type MockEventRepo struct {
	mock.Mock
}

type MockEventRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventRepo) EXPECT() *MockEventRepo_Expecter {
	return &MockEventRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockEventRepo
func (_mock *MockEventRepo) Create(ctx context.Context, e *domain.Event) error {
	ret := _mock.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Event) error); ok {
		r0 = returnFunc(ctx, e)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockEventRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - e *domain.Event
func (_e *MockEventRepo_Expecter) Create(ctx interface{}, e interface{}) *MockEventRepo_Create_Call {
	return &MockEventRepo_Create_Call{Call: _e.mock.On("Create", ctx, e)}
}

func (_c *MockEventRepo_Create_Call) Run(run func(ctx context.Context, e *domain.Event)) *MockEventRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Event
		if args[1] != nil {
			arg1 = args[1].(*domain.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventRepo_Create_Call) Return(err error) *MockEventRepo_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventRepo_Create_Call) RunAndReturn(run func(ctx context.Context, e *domain.Event) error) *MockEventRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockEventRepo
func (_mock *MockEventRepo) GetByID(ctx context.Context, id string) (*domain.Event, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Event, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Event); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventRepo_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockEventRepo_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockEventRepo_Expecter) GetByID(ctx interface{}, id interface{}) *MockEventRepo_GetByID_Call {
	return &MockEventRepo_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockEventRepo_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockEventRepo_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventRepo_GetByID_Call) Return(event *domain.Event, err error) *MockEventRepo_GetByID_Call {
	_c.Call.Return(event, err)
	return _c
}

func (_c *MockEventRepo_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*domain.Event, error)) *MockEventRepo_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetDetails provides a mock function for the type MockEventRepo
func (_mock *MockEventRepo) GetDetails(ctx context.Context, eventID string) (*domain.EventDetails, error) {
	ret := _mock.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for GetDetails")
	}

	var r0 *domain.EventDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.EventDetails, error)); ok {
		return returnFunc(ctx, eventID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.EventDetails); ok {
		r0 = returnFunc(ctx, eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.EventDetails)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventRepo_GetDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDetails'
type MockEventRepo_GetDetails_Call struct {
	*mock.Call
}

// GetDetails is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
func (_e *MockEventRepo_Expecter) GetDetails(ctx interface{}, eventID interface{}) *MockEventRepo_GetDetails_Call {
	return &MockEventRepo_GetDetails_Call{Call: _e.mock.On("GetDetails", ctx, eventID)}
}

func (_c *MockEventRepo_GetDetails_Call) Run(run func(ctx context.Context, eventID string)) *MockEventRepo_GetDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventRepo_GetDetails_Call) Return(eventDetails *domain.EventDetails, err error) *MockEventRepo_GetDetails_Call {
	_c.Call.Return(eventDetails, err)
	return _c
}

func (_c *MockEventRepo_GetDetails_Call) RunAndReturn(run func(ctx context.Context, eventID string) (*domain.EventDetails, error)) *MockEventRepo_GetDetails_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockEventRepo
func (_mock *MockEventRepo) List(ctx context.Context) ([]*domain.Event, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*domain.Event, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*domain.Event); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventRepo_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockEventRepo_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockEventRepo_Expecter) List(ctx interface{}) *MockEventRepo_List_Call {
	return &MockEventRepo_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockEventRepo_List_Call) Run(run func(ctx context.Context)) *MockEventRepo_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventRepo_List_Call) Return(events []*domain.Event, err error) *MockEventRepo_List_Call {
	_c.Call.Return(events, err)
	return _c
}

func (_c *MockEventRepo_List_Call) RunAndReturn(run func(ctx context.Context) ([]*domain.Event, error)) *MockEventRepo_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBookingNotifier creates a new instance of MockBookingNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingNotifier {
	mock := &MockBookingNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBookingNotifier is an autogenerated mock type for the BookingNotifier type
type MockBookingNotifier struct {
	mock.Mock
}

type MockBookingNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingNotifier) EXPECT() *MockBookingNotifier_Expecter {
	return &MockBookingNotifier_Expecter{mock: &_m.Mock}
}

// NotifyBookingCancelled provides a mock function for the type MockBookingNotifier
func (_mock *MockBookingNotifier) NotifyBookingCancelled(ctx context.Context, user *domain.User, event *domain.Event) {
	_mock.Called(ctx, user, event)
	return
}

// MockBookingNotifier_NotifyBookingCancelled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyBookingCancelled'
type MockBookingNotifier_NotifyBookingCancelled_Call struct {
	*mock.Call
}

// NotifyBookingCancelled is a helper method to define mock.On call
//   - ctx context.Context
//   - user *domain.User
//   - event *domain.Event
func (_e *MockBookingNotifier_Expecter) NotifyBookingCancelled(ctx interface{}, user interface{}, event interface{}) *MockBookingNotifier_NotifyBookingCancelled_Call {
	return &MockBookingNotifier_NotifyBookingCancelled_Call{Call: _e.mock.On("NotifyBookingCancelled", ctx, user, event)}
}

func (_c *MockBookingNotifier_NotifyBookingCancelled_Call) Run(run func(ctx context.Context, user *domain.User, event *domain.Event)) *MockBookingNotifier_NotifyBookingCancelled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.User
		if args[1] != nil {
			arg1 = args[1].(*domain.User)
		}
		var arg2 *domain.Event
		if args[2] != nil {
			arg2 = args[2].(*domain.Event)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBookingNotifier_NotifyBookingCancelled_Call) Return() *MockBookingNotifier_NotifyBookingCancelled_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBookingNotifier_NotifyBookingCancelled_Call) RunAndReturn(run func(ctx context.Context, user *domain.User, event *domain.Event)) *MockBookingNotifier_NotifyBookingCancelled_Call {
	_c.Run(run)
	return _c
}

// NotifyBookingConfirmed provides a mock function for the type MockBookingNotifier
func (_mock *MockBookingNotifier) NotifyBookingConfirmed(ctx context.Context, user *domain.User, event *domain.Event) {
	_mock.Called(ctx, user, event)
	return
}

// MockBookingNotifier_NotifyBookingConfirmed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyBookingConfirmed'
type MockBookingNotifier_NotifyBookingConfirmed_Call struct {
	*mock.Call
}

// NotifyBookingConfirmed is a helper method to define mock.On call
//   - ctx context.Context
//   - user *domain.User
//   - event *domain.Event
func (_e *MockBookingNotifier_Expecter) NotifyBookingConfirmed(ctx interface{}, user interface{}, event interface{}) *MockBookingNotifier_NotifyBookingConfirmed_Call {
	return &MockBookingNotifier_NotifyBookingConfirmed_Call{Call: _e.mock.On("NotifyBookingConfirmed", ctx, user, event)}
}

func (_c *MockBookingNotifier_NotifyBookingConfirmed_Call) Run(run func(ctx context.Context, user *domain.User, event *domain.Event)) *MockBookingNotifier_NotifyBookingConfirmed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.User
		if args[1] != nil {
			arg1 = args[1].(*domain.User)
		}
		var arg2 *domain.Event
		if args[2] != nil {
			arg2 = args[2].(*domain.Event)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBookingNotifier_NotifyBookingConfirmed_Call) Return() *MockBookingNotifier_NotifyBookingConfirmed_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBookingNotifier_NotifyBookingConfirmed_Call) RunAndReturn(run func(ctx context.Context, user *domain.User, event *domain.Event)) *MockBookingNotifier_NotifyBookingConfirmed_Call {
	_c.Run(run)
	return _c
}

// NotifyBookingCreated provides a mock function for the type MockBookingNotifier
func (_mock *MockBookingNotifier) NotifyBookingCreated(ctx context.Context, user *domain.User, event *domain.Event) {
	_mock.Called(ctx, user, event)
	return
}

// MockBookingNotifier_NotifyBookingCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyBookingCreated'
type MockBookingNotifier_NotifyBookingCreated_Call struct {
	*mock.Call
}

// NotifyBookingCreated is a helper method to define mock.On call
//   - ctx context.Context
//   - user *domain.User
//   - event *domain.Event
func (_e *MockBookingNotifier_Expecter) NotifyBookingCreated(ctx interface{}, user interface{}, event interface{}) *MockBookingNotifier_NotifyBookingCreated_Call {
	return &MockBookingNotifier_NotifyBookingCreated_Call{Call: _e.mock.On("NotifyBookingCreated", ctx, user, event)}
}

func (_c *MockBookingNotifier_NotifyBookingCreated_Call) Run(run func(ctx context.Context, user *domain.User, event *domain.Event)) *MockBookingNotifier_NotifyBookingCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.User
		if args[1] != nil {
			arg1 = args[1].(*domain.User)
		}
		var arg2 *domain.Event
		if args[2] != nil {
			arg2 = args[2].(*domain.Event)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBookingNotifier_NotifyBookingCreated_Call) Return() *MockBookingNotifier_NotifyBookingCreated_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBookingNotifier_NotifyBookingCreated_Call) RunAndReturn(run func(ctx context.Context, user *domain.User, event *domain.Event)) *MockBookingNotifier_NotifyBookingCreated_Call {
	_c.Run(run)
	return _c
}

// NewMockUserRepo creates a new instance of MockUserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepo {
	mock := &MockUserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepo is an autogenerated mock type for the UserRepo type
type MockUserRepo struct {
	mock.Mock
}

type MockUserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepo) EXPECT() *MockUserRepo_Expecter {
	return &MockUserRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) Create(ctx context.Context, user *domain.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user *domain.User
func (_e *MockUserRepo_Expecter) Create(ctx interface{}, user interface{}) *MockUserRepo_Create_Call {
	return &MockUserRepo_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *MockUserRepo_Create_Call) Run(run func(ctx context.Context, user *domain.User)) *MockUserRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.User
		if args[1] != nil {
			arg1 = args[1].(*domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_Create_Call) Return(err error) *MockUserRepo_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_Create_Call) RunAndReturn(run func(ctx context.Context, user *domain.User) error) *MockUserRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) GetByID(ctx context.Context, id string) (*domain.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockUserRepo_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserRepo_Expecter) GetByID(ctx interface{}, id interface{}) *MockUserRepo_GetByID_Call {
	return &MockUserRepo_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockUserRepo_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockUserRepo_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_GetByID_Call) Return(user *domain.User, err error) *MockUserRepo_GetByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepo_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*domain.User, error)) *MockUserRepo_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUsername provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) GetByUsername(ctx context.Context, username string) (*domain.User, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetByUsername")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_GetByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUsername'
type MockUserRepo_GetByUsername_Call struct {
	*mock.Call
}

// GetByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUserRepo_Expecter) GetByUsername(ctx interface{}, username interface{}) *MockUserRepo_GetByUsername_Call {
	return &MockUserRepo_GetByUsername_Call{Call: _e.mock.On("GetByUsername", ctx, username)}
}

func (_c *MockUserRepo_GetByUsername_Call) Run(run func(ctx context.Context, username string)) *MockUserRepo_GetByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_GetByUsername_Call) Return(user *domain.User, err error) *MockUserRepo_GetByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepo_GetByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (*domain.User, error)) *MockUserRepo_GetByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) List(ctx context.Context) ([]*domain.User, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*domain.User, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*domain.User); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockUserRepo_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUserRepo_Expecter) List(ctx interface{}) *MockUserRepo_List_Call {
	return &MockUserRepo_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockUserRepo_List_Call) Run(run func(ctx context.Context)) *MockUserRepo_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserRepo_List_Call) Return(users []*domain.User, err error) *MockUserRepo_List_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserRepo_List_Call) RunAndReturn(run func(ctx context.Context) ([]*domain.User, error)) *MockUserRepo_List_Call {
	_c.Call.Return(run)
	return _c
}
